analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7163649
  brandStrength: 0.9853703209664673
  lightness: 0.566595
  brandColors:
    - '#90A4BC'
    - '#C6D8E8'
    - '#1F1F17'
    - '#775342'
    - '#BD8976'
  rhythmicContrast: 0.119631
typography_spectrum: 0.8888292
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
favicon: null
name: tryckytryck
